### ISSUE TITLE
Avoid text selection on Repositories Card's

### ISSUE THREAD

**Issue by angelmtztrc** [angelmtztrc/portfolio#17]
Right now, if you select the text in a card it will be highlighted, and that looks very ugly, so will be better if we avoid this thing.

![image](https://user-images.githubusercontent.com/65056245/135734363-0f1c03f8-92c8-4bf1-8591-ab9a366f5b4a.png)

**Comment by darkuzdev** [comment]
Could i take this issue?

**Comment by angelmtztrc** [comment]
Sure, go ahead!
